site_name: My Docs
site_url: https://dummy.github.io
site_author: you
site_description: a short description of your website

nav:
  - Index: index.md
  - About: about.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

extra_javascript:
  - myscript.js